import User from "@/models/User";
import Property from "@/models/Property";
import Product from "@/models/Product";

let isSeeded = false;

export async function seedDatabase(force: boolean = false) {
  if (isSeeded && !force) return;

  try {
    // 1. Admin User
    const adminCount = await User.countDocuments();
    if (adminCount === 0) {
      await User.create({
        name: "Admin Support",
        email: "admin@khurjadeals.com",
        password: "KhurjaDeals@2026",
        role: "admin",
        status: "active",
      });
      console.log("Seeded admin user.");
    }

    // 2. Properties Seeding (Minimum 15 properties)
    const propertyCount = await Property.countDocuments();
    if (propertyCount < 15 || force) {
      if (force) {
        await Property.deleteMany({});
      }
      const mockProperties = [
        {
          title: "Premium Commercial Shop on G.T. Road",
          slug: "premium-commercial-shop-on-gt-road",
          description: "A spacious 200 sq. yard commercial shop located in the prime market area of G.T. Road, Khurja. High foot traffic, ideal for retail or showrooms.",
          type: "commercial",
          listingType: "sell",
          status: "active",
          price: 4500000,
          area: 1800,
          areaUnit: "sqft",
          location: "GT Road",
          address: "Shop No. 42, GT Road, Khurja, UP",
          images: ["https://images.unsplash.com/photo-1582407947304-fd86f028f716?auto=format&fit=crop&w=800&q=80"],
          features: ["Parking Space", "Main Road Face", "Power Backup"],
          contactName: "Ramesh Sharma",
          contactPhone: "917906896546",
          isFeatured: true,
          views: 120,
        },
        {
          title: "Residential Plot for Sale near Khurja Junction",
          slug: "residential-plot-near-khurja-junction",
          description: "150 Gaj residential plot available in a secure gated colony near Khurja Junction with wide roads and green parks.",
          type: "plot",
          listingType: "sell",
          status: "active",
          price: 1800000,
          area: 1350,
          areaUnit: "sqft",
          location: "Junction Road",
          address: "Plot 89, Shubham Vihar Colony, Junction Road, Khurja",
          images: ["https://images.unsplash.com/photo-1500382017468-9049fed747ef?auto=format&fit=crop&w=800&q=80"],
          features: ["Gated Colony", "24ft Wide Road", "Park Facing"],
          contactName: "Shubham Gupta",
          contactPhone: "917906896546",
          isFeatured: true,
          views: 95,
        },
        {
          title: "Spacious 3 BHK Independent House for Rent",
          slug: "spacious-3-bhk-independent-house-for-rent",
          description: "Beautifully constructed double-story 3 BHK independent house for rent in a peaceful residential area of Khurja.",
          type: "residential",
          listingType: "rent",
          status: "active",
          price: 12000,
          area: 1600,
          areaUnit: "sqft",
          location: "Subhash Road",
          address: "House 12B, Subhash Road, Khurja",
          images: ["https://images.unsplash.com/photo-1564013799919-ab600027ffc6?auto=format&fit=crop&w=800&q=80"],
          features: ["Modular Kitchen", "Balcony", "Car Parking"],
          contactName: "Devender Singh",
          contactPhone: "917906896546",
          isFeatured: false,
          views: 64,
        },
        {
          title: "Prime Agricultural Land near Aligarh Bypass",
          slug: "prime-agricultural-land-near-aligarh-bypass",
          description: " Fertile 5 Bigha agricultural land suitable for farming, warehouse, or cold storage project. Direct canal water access.",
          type: "agricultural",
          listingType: "sell",
          status: "active",
          price: 7500000,
          area: 32000,
          areaUnit: "sqft",
          location: "Aligarh Road",
          address: "Khasra 402, Aligarh Bypass Road, Khurja",
          images: ["https://images.unsplash.com/photo-1500382017468-9049fed747ef?auto=format&fit=crop&w=800&q=80"],
          features: ["Tube Well", "Road Touch", "Clear Title"],
          contactName: "Chaudhary Mahipal",
          contactPhone: "917906896546",
          isFeatured: true,
          views: 110,
        },
        {
          title: "Commercial Godown / Warehouse for Rent",
          slug: "commercial-godown-warehouse-for-rent",
          description: "Heavy duty 4000 sq ft industrial godown space available for lease near Ceramic Industrial Area, Khurja.",
          type: "commercial",
          listingType: "lease",
          status: "active",
          price: 35000,
          area: 4000,
          areaUnit: "sqft",
          location: "Industrial Area",
          address: "Plot 14, Ceramic Zone, Khurja",
          images: ["https://images.unsplash.com/photo-1586528116311-ad8dd3c8310d?auto=format&fit=crop&w=800&q=80"],
          features: ["High Ceiling", "Truck Loading Dock", "3-Phase Power"],
          contactName: "Sanjay Ceramics Pvt Ltd",
          contactPhone: "917906896546",
          isFeatured: false,
          views: 82,
        },
        {
          title: "Modern 2 BHK Apartment for Sale in Navjeevan City",
          slug: "modern-2-bhk-apartment-navjeevan-city",
          description: "Ready to move 2 BHK flat with modern amenities, 24x7 security, power backup, and lift facility.",
          type: "residential",
          listingType: "sell",
          status: "active",
          price: 2800000,
          area: 1050,
          areaUnit: "sqft",
          location: "Junction Road",
          address: "Flat 304, Tower B, Navjeevan City, Khurja",
          images: ["https://images.unsplash.com/photo-1545324418-cc1a3fa10c00?auto=format&fit=crop&w=800&q=80"],
          features: ["Lift", "Security Guard", "Gym", "Clubhouse"],
          contactName: "Pankaj Sharma",
          contactPhone: "917906896546",
          isFeatured: true,
          views: 140,
        },
        {
          title: "Corner Market Shop for Sale on Junction Road",
          slug: "corner-market-shop-sale-junction-road",
          description: "Double side open corner shop in prime retail market. High daily footfall, dual shutters.",
          type: "commercial",
          listingType: "sell",
          status: "active",
          price: 3200000,
          area: 450,
          areaUnit: "sqft",
          location: "Junction Road",
          address: "Shop 12, Main Market, Junction Road, Khurja",
          images: ["https://images.unsplash.com/photo-1555396273-367ea4eb4db5?auto=format&fit=crop&w=800&q=80"],
          features: ["Corner Property", "Double Shutter", "Prime Location"],
          contactName: "Vikas Agrawal",
          contactPhone: "917906896546",
          isFeatured: false,
          views: 75,
        },
        {
          title: "Residential Land 200 Sq Yd in Govindpuri Colony",
          slug: "residential-land-govindpuri-colony",
          description: "Prime residential plot ready for instant home construction. Electricity & sewer line connected.",
          type: "plot",
          listingType: "sell",
          status: "active",
          price: 2200000,
          area: 1800,
          areaUnit: "sqft",
          location: "Govindpuri",
          address: "Plot 45, Govindpuri Extension, Khurja",
          images: ["https://images.unsplash.com/photo-1500382017468-9049fed747ef?auto=format&fit=crop&w=800&q=80"],
          features: ["Sewerage Line", "Street Lights", "Wide Road"],
          contactName: "Anil Varshney",
          contactPhone: "917906896546",
          isFeatured: false,
          views: 58,
        },
        {
          title: "1 BHK Furnished Flat for Rent near Bus Stand",
          slug: "1-bhk-furnished-flat-rent-bus-stand",
          description: "Fully furnished 1 BHK apartment with AC, bed, sofa, and kitchen appliances. Ideal for single professionals or small families.",
          type: "residential",
          listingType: "rent",
          status: "active",
          price: 7500,
          area: 550,
          areaUnit: "sqft",
          location: "GT Road",
          address: "Flat 102, Near Old Bus Stand, Khurja",
          images: ["https://images.unsplash.com/photo-1522708323590-d24dbb6b0267?auto=format&fit=crop&w=800&q=80"],
          features: ["Fully Furnished", "AC Included", "Wi-Fi Ready"],
          contactName: "Manoj Solanki",
          contactPhone: "917906896546",
          isFeatured: false,
          views: 92,
        },
        {
          title: "Industrial Plot 1000 Sq Mtr for Lease",
          slug: "industrial-plot-1000-sq-mtr-for-lease",
          description: "UPSIDC approved industrial plot available for long term lease for pottery factory or packaging industry.",
          type: "commercial",
          listingType: "lease",
          status: "active",
          price: 45000,
          area: 10760,
          areaUnit: "sqft",
          location: "Industrial Area",
          address: "Plot 88-C, UPSIDC Industrial Zone, Khurja",
          images: ["https://images.unsplash.com/photo-1586528116311-ad8dd3c8310d?auto=format&fit=crop&w=800&q=80"],
          features: ["UPSIDC Approved", "Industrial Power Feeder", "Wide Entry"],
          contactName: "Deepak Industrial Corp",
          contactPhone: "917906896546",
          isFeatured: true,
          views: 130,
        },
        {
          title: "Luxury 4 BHK Villa for Sale in Green Park Colony",
          slug: "luxury-4-bhk-villa-green-park-colony",
          description: "Exclusive duplex villa featuring modern interior, modular kitchen, lush lawn, and 2-car garage.",
          type: "residential",
          listingType: "sell",
          status: "active",
          price: 6500000,
          area: 2700,
          areaUnit: "sqft",
          location: "Subhash Road",
          address: "Villa 5, Green Park Enclave, Khurja",
          images: ["https://images.unsplash.com/photo-1600596542815-ffad4c1539a9?auto=format&fit=crop&w=800&q=80"],
          features: ["Private Garden", "Duplex Design", "2 Car Parking"],
          contactName: "Rajeshwar Prasad",
          contactPhone: "917906896546",
          isFeatured: true,
          views: 210,
        },
        {
          title: "Retail Shop for Rent in Main Grain Market (Mandi)",
          slug: "retail-shop-rent-grain-market-mandi",
          description: "Prime ground floor retail shop ideal for grocery store, seed business, or office.",
          type: "commercial",
          listingType: "rent",
          status: "active",
          price: 15000,
          area: 350,
          areaUnit: "sqft",
          location: "Mandi Road",
          address: "Shop 77, Grain Mandi Complex, Khurja",
          images: ["https://images.unsplash.com/photo-1555396273-367ea4eb4db5?auto=format&fit=crop&w=800&q=80"],
          features: ["Ground Floor", "High Loading Capacity", "Water Supply"],
          contactName: "Satish Chand",
          contactPhone: "917906896546",
          isFeatured: false,
          views: 54,
        },
        {
          title: "Farmland 10 Bigha with Borewell on Jewar Road",
          slug: "farmland-10-bigha-borewell-jewar-road",
          description: "High fertility agricultural land located near proposed Jewar airport connectivity corridor.",
          type: "agricultural",
          listingType: "sell",
          status: "active",
          price: 12500000,
          area: 64000,
          areaUnit: "sqft",
          location: "Jewar Road",
          address: "Village Aurangpur, Jewar Road, Khurja",
          images: ["https://images.unsplash.com/photo-1500382017468-9049fed747ef?auto=format&fit=crop&w=800&q=80"],
          features: ["Borewell Installed", "Jewar Corridor", "Clear Ownership"],
          contactName: "Chaudhary Vijendra Singh",
          contactPhone: "917906896546",
          isFeatured: true,
          views: 175,
        },
        {
          title: "Affordable 100 Gaj Plot in Anand Vihar",
          slug: "affordable-100-gaj-plot-anand-vihar",
          description: "Budget-friendly plot suitable for nuclear family home or investment near school and hospital.",
          type: "plot",
          listingType: "sell",
          status: "active",
          price: 1100000,
          area: 900,
          areaUnit: "sqft",
          location: "Junction Road",
          address: "Plot 104, Anand Vihar Colony, Khurja",
          images: ["https://images.unsplash.com/photo-1500382017468-9049fed747ef?auto=format&fit=crop&w=800&q=80"],
          features: ["Near School", "Electric Poles", "Clear Title"],
          contactName: "Mohit Jain",
          contactPhone: "917906896546",
          isFeatured: false,
          views: 88,
        },
        {
          title: "2 BHK Builder Floor for Rent on GT Road",
          slug: "2-bhk-builder-floor-rent-gt-road",
          description: "First floor 2 BHK flat with balcony and reserved scooter parking.",
          type: "residential",
          listingType: "rent",
          status: "active",
          price: 8500,
          area: 900,
          areaUnit: "sqft",
          location: "GT Road",
          address: "Floor 1, Plot 34, GT Road, Khurja",
          images: ["https://images.unsplash.com/photo-1564013799919-ab600027ffc6?auto=format&fit=crop&w=800&q=80"],
          features: ["Balcony", "Separate Meter", "Near Market"],
          contactName: "Sunil Kumar",
          contactPhone: "917906896546",
          isFeatured: false,
          views: 61,
        },
        {
          title: "Commercial Hall 1500 Sq Ft for Lease on Subhash Road",
          slug: "commercial-hall-1500-sq-ft-lease-subhash-road",
          description: "Open floor commercial hall suitable for gym, coaching institute, bank branch, or diagnostic lab.",
          type: "commercial",
          listingType: "lease",
          status: "active",
          price: 25000,
          area: 1500,
          areaUnit: "sqft",
          location: "Subhash Road",
          address: "2nd Floor, Commercial Plaza, Subhash Road, Khurja",
          images: ["https://images.unsplash.com/photo-1497366216548-37526070297c?auto=format&fit=crop&w=800&q=80"],
          features: ["Open Floor", "Washroom", "Glass Front"],
          contactName: "Dr. Alok Sharma",
          contactPhone: "917906896546",
          isFeatured: false,
          views: 99,
        }
      ];

      await Property.insertMany(mockProperties);
      console.log(`Database Seeded: Created ${mockProperties.length} mock properties.`);
    }

    // 3. Products Seeding (Minimum 15 products)
    const productCount = await Product.countDocuments();
    if (productCount < 15 || force) {
      if (force) {
        await Product.deleteMany({});
      }
      const mockProducts = [
        {
          title: "Traditional Blue Ceramic Flower Pot",
          slug: "traditional-blue-ceramic-flower-pot",
          description: "Beautiful hand-painted blue ceramic flower pot crafted by Khurja artisans. Durable, glaze-finished, 12 inches tall.",
          category: "Pottery & Ceramics",
          condition: "new",
          status: "active",
          price: 350,
          images: ["https://images.unsplash.com/photo-1578749556568-bc2c40e68b61?auto=format&fit=crop&w=800&q=80"],
          location: "Pottery Market",
          contactName: "Khurja Artisans Coop",
          contactPhone: "917906896546",
          isFeatured: true,
          views: 180,
        },
        {
          title: "Set of 6 Glazed Tea/Coffee Mugs",
          slug: "set-of-6-glazed-tea-coffee-mugs",
          description: "High-quality microwave-safe glazed ceramic mugs in dual-tone colors crafted in Khurja.",
          category: "Pottery & Ceramics",
          condition: "new",
          status: "active",
          price: 280,
          images: ["https://images.unsplash.com/photo-1514432324607-a09d9b4aefdd?auto=format&fit=crop&w=800&q=80"],
          location: "Pottery Market",
          contactName: "Pottery Hub Sales",
          contactPhone: "917906896546",
          isFeatured: true,
          views: 145,
        },
        {
          title: "Used Hero Ranger Mountain Bicycle",
          slug: "used-hero-ranger-mountain-bicycle",
          description: "Hero Ranger cycle in excellent running condition. 18 speed gear shift, new front tires.",
          category: "Bicycles & Tech",
          condition: "used",
          status: "active",
          price: 3200,
          images: ["https://images.unsplash.com/photo-1485965120184-e220f721d03e?auto=format&fit=crop&w=800&q=80"],
          location: "GT Road",
          contactName: "Amit Kumar",
          contactPhone: "917906896546",
          isFeatured: false,
          views: 42,
        },
        {
          title: "Handmade Ceramic Dinner Set (18 Pieces)",
          slug: "handmade-ceramic-dinner-set-18-pieces",
          description: "Premium stoneware dinner set including plates, bowls, and serving dishes with Royal Khurja blue floral print.",
          category: "Pottery & Ceramics",
          condition: "new",
          status: "active",
          price: 1850,
          images: ["https://images.unsplash.com/photo-1610701596007-11502861dcfa?auto=format&fit=crop&w=800&q=80"],
          location: "Pottery Market",
          contactName: "Khurja Pottery Emporium",
          contactPhone: "917906896546",
          isFeatured: true,
          views: 210,
        },
        {
          title: "Samsung 32 Inch Smart LED TV (Used)",
          slug: "samsung-32-inch-smart-led-tv-used",
          description: "Samsung 32-inch HD Smart TV in crisp working condition with original remote and wall mount bracket.",
          category: "Vehicles & Tech",
          condition: "used",
          status: "active",
          price: 7800,
          images: ["https://images.unsplash.com/photo-1593784991095-a205069470b6?auto=format&fit=crop&w=800&q=80"],
          location: "Subhash Road",
          contactName: "Gaurav Electronics",
          contactPhone: "917906896546",
          isFeatured: false,
          views: 98,
        },
        {
          title: "Honda Activa 5G (2019 Model)",
          slug: "honda-activa-5g-2019-model",
          description: "Single owner Honda Activa 5G in excellent condition, 28,000 km driven, fresh battery and insurance valid.",
          category: "Vehicles & Tech",
          condition: "used",
          status: "active",
          price: 38000,
          images: ["https://images.unsplash.com/photo-1558981403-c5f9899a28bc?auto=format&fit=crop&w=800&q=80"],
          location: "Junction Road",
          contactName: "Nitin Sharma",
          contactPhone: "917906896546",
          isFeatured: true,
          views: 310,
        },
        {
          title: "Decorative Khurja Ceramic Water Fountain",
          slug: "decorative-khurja-ceramic-water-fountain",
          description: "Indoor 3-tier ceramic water fountain with LED light and submersible pump. Enhances home decor.",
          category: "Pottery & Ceramics",
          condition: "new",
          status: "active",
          price: 1250,
          images: ["https://images.unsplash.com/photo-1578749556568-bc2c40e68b61?auto=format&fit=crop&w=800&q=80"],
          location: "Pottery Market",
          contactName: "Classic Ceramics",
          contactPhone: "917906896546",
          isFeatured: false,
          views: 74,
        },
        {
          title: "LG 260L Double Door Refrigerator",
          slug: "lg-260l-double-door-refrigerator",
          description: "Frost-free double door fridge, 3-star energy rating, works perfectly without stabilizer.",
          category: "Vehicles & Tech",
          condition: "used",
          status: "active",
          price: 11500,
          images: ["https://images.unsplash.com/photo-1584992236310-6edddc08acff?auto=format&fit=crop&w=800&q=80"],
          location: "GT Road",
          contactName: "Praveen Kumar",
          contactPhone: "917906896546",
          isFeatured: false,
          views: 86,
        },
        {
          title: "Handcrafted Terracotta Oil Burner & Aroma Diffuser",
          slug: "handcrafted-terracotta-oil-burner-aroma-diffuser",
          description: "Set of 2 ceramic aroma diffusers with tea light candles and lavender essential oil bottle.",
          category: "Pottery & Ceramics",
          condition: "new",
          status: "active",
          price: 220,
          images: ["https://images.unsplash.com/photo-1508746829417-e6f548d8d6ed?auto=format&fit=crop&w=800&q=80"],
          location: "Pottery Market",
          contactName: "Organic Khurja Craft",
          contactPhone: "917906896546",
          isFeatured: false,
          views: 52,
        },
        {
          title: "Whirlpool 7 Kg Fully Automatic Washing Machine",
          slug: "whirlpool-7kg-fully-automatic-washing-machine",
          description: "Top load washing machine in clean condition, 6 months warranty left, scratchless body.",
          category: "Vehicles & Tech",
          condition: "used",
          status: "active",
          price: 8900,
          images: ["https://images.unsplash.com/photo-1626806787461-102c1bfaaea1?auto=format&fit=crop&w=800&q=80"],
          location: "Govindpuri",
          contactName: "Sanjay Solanki",
          contactPhone: "917906896546",
          isFeatured: false,
          views: 115,
        },
        {
          title: "Large Ceramic Planters Pot Set (Pack of 3)",
          slug: "large-ceramic-planters-pot-set-pack-of-3",
          description: "Set of 3 outdoor glazed garden planters in terracotta finish. Weatherproof and durable.",
          category: "Pottery & Ceramics",
          condition: "new",
          status: "active",
          price: 950,
          images: ["https://images.unsplash.com/photo-1485955900006-10f4d324d411?auto=format&fit=crop&w=800&q=80"],
          location: "Pottery Market",
          contactName: "Green Earth Pottery",
          contactPhone: "917906896546",
          isFeatured: true,
          views: 160,
        },
        {
          title: "Royal Enfield Bullet 350 ES (2018)",
          slug: "royal-enfield-bullet-350-es-2018",
          description: "Black Royal Enfield Bullet 350 Electric Start in showroom condition, original silencer + extra bend pipe.",
          category: "Vehicles & Tech",
          condition: "used",
          status: "active",
          price: 112000,
          images: ["https://images.unsplash.com/photo-1558981806-ec527fa84c39?auto=format&fit=crop&w=800&q=80"],
          location: "GT Road",
          contactName: "Captain Vikram",
          contactPhone: "917906896546",
          isFeatured: true,
          views: 420,
        },
        {
          title: "Hand-Painted Ceramic Soup Bowl Set with Spoons",
          slug: "hand-painted-ceramic-soup-bowl-set-spoons",
          description: "Set of 6 deep soup bowls with matching ceramic spoons, microwave safe and dishwasher safe.",
          category: "Pottery & Ceramics",
          condition: "new",
          status: "active",
          price: 480,
          images: ["https://images.unsplash.com/photo-1578749556568-bc2c40e68b61?auto=format&fit=crop&w=800&q=80"],
          location: "Pottery Market",
          contactName: "Master Craftsmen Guild",
          contactPhone: "917906896546",
          isFeatured: false,
          views: 89,
        },
        {
          title: "Wooden Study Table with Bookshelf Unit",
          slug: "wooden-study-table-with-bookshelf-unit",
          description: "Solid Sheesham wood computer/study table with drawer, cabinet, and top bookshelf storage.",
          category: "Furniture & Decor",
          condition: "used",
          status: "active",
          price: 4200,
          images: ["https://images.unsplash.com/photo-1518455027359-f3f8164ba6bd?auto=format&fit=crop&w=800&q=80"],
          location: "Subhash Road",
          contactName: "Rakesh Furniture",
          contactPhone: "917906896546",
          isFeatured: false,
          views: 73,
        },
        {
          title: "Designer Ceramic Tea Jar & Pickle Container Set",
          slug: "designer-ceramic-tea-jar-pickle-container-set",
          description: "Traditional ceramic pickle (Achar) jars with airtight wooden lids, set of 4.",
          category: "Pottery & Ceramics",
          condition: "new",
          status: "active",
          price: 390,
          images: ["https://images.unsplash.com/photo-1514432324607-a09d9b4aefdd?auto=format&fit=crop&w=800&q=80"],
          location: "Pottery Market",
          contactName: "Khurja Heritage Store",
          contactPhone: "917906896546",
          isFeatured: false,
          views: 67,
        },
        {
          title: "Dell Core i5 Laptop 8GB RAM 256GB SSD",
          slug: "dell-core-i5-laptop-8gb-ram-256gb-ssd",
          description: "Dell Latitude laptop, Intel Core i5 8th Gen, 8GB DDR4 RAM, 256GB NVMe SSD, Windows 11 Pro installed.",
          category: "Vehicles & Tech",
          condition: "used",
          status: "active",
          price: 18500,
          images: ["https://images.unsplash.com/photo-1496181133206-80ce9b88a853?auto=format&fit=crop&w=800&q=80"],
          location: "Junction Road",
          contactName: "Tech Hub Khurja",
          contactPhone: "917906896546",
          isFeatured: true,
          views: 195,
        }
      ];

      await Product.insertMany(mockProducts);
      console.log(`Database Seeded: Created ${mockProducts.length} mock bazaar products.`);
    }

    isSeeded = true;
  } catch (error) {
    console.error("Database seeding failed:", error);
  }
}
